add_newline = false

# A minimal left prompt
# format = """$directory$character"""
palette = "catppuccin_coal"
# move the rest of the prompt to the right
# right_format = """$all"""

# [aws]
# format = 'on [$symbol($profile )(\($region\) )]($style)'
# style = 'bold blue'
# symbol = "  "

# [golang]
# format = '[ ](bold cyan)'

# [docker_context]
# disabled = true

[palettes.catppuccin_coal]
# Same as catppuccin mocha for these
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
# Coal variant: https://gist.github.com/RingOfStorms/b2ff0c4e37f5be9f985c72c3ec9a3e62
text = "#e0e0e0"
subtext1 = "#cccccc"
subtext0 = "#b8b8b8"
overlay2 = "#a3a3a3"
overlay1 = "#8c8c8c"
overlay0 = "#787878"
surface2 = "#636363"
surface1 = "#4f4f4f"
surface0 = "#3b3b3b"
base = "#262626"
mantle = "#1f1f1f"
crust = "#171717"
