# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

let
  rgo_keyboard_vid = "0911";
  rgo_keyboard_pid = "2188";
  rgo_hub_vid = "05e3";
  rgo_hub_pid = "0608";
in
{
  services.keyd = {
    enable = true;
    # `keyd monitor` to get new keys to remap
    keyboards = {
      rgo_sino_keyboard = {
      	ids = [ "0911:2188" "05e3:0608" ];
	settings = {
	  main = {
	    "\\" = "enter";
	    "102nd" = "\\";
	  };
	};
      };
    };
  };
}
