#!/usr/bin/env bash 

# Profile is run on login and not on every interactive shell. Use zshrc for things not needing login
# (float terms in nvim will not source this file.)

# Git config options
git config --global core.excludesfile ~/.config/git/ignore
git config --global core.config ~/.config/git/config


# TODO make this work better
# Remarkable Screenshot
resnap () {
# output_jpg	File to save screenshot to (default resnap.jpg)
# -v --version	Display version and exit
# -i		path to ssh pubkey
# -r		Address of reMarkable (default 10.11.99.1)
# -h --help	Display usage and exit
  /Users/joshua.bell/other/resnap.sh
}



