#!/usr/bin/env bash 

export JAVA_HOME=$(/usr/libexec/java_home)
export JRE_HOME=$(/usr/libexec/java_home)

# gradle
gradle () {
  if test -f ".env.local"; then
      source .env.local
  fi

  GITHUB_USERNAME=${GITHUB_USERNAME} GITHUB_TOKEN=${GITHUB_TOKEN} ./gradlew $@
}

# minecraft stuff
paper_latest () {
  rm *paper*.jar
  curl -o paper.jar https://papermc.io/api/v1/paper/1.16.4/latest/download
}

remote_down () {
  diskutil umount force ~/Desktop/mc_remote > /dev/null
  rm -rf ~/Desktop/mc_remote
}

remote_mount () {
  remote_down

  if [ $1 = "joeb" ]; then
    echo "Mounting joeb to desktop..."
    sshfs joeb:/ ~/Desktop/mc_remote -o volname=joeb_remote
  fi
  if [ $1 = "joebr" ]; then
    echo "Mounting joebr to desktop..."
    sshfs joebr:/ ~/Desktop/mc_remote -o volname=joebr_remote
  fi
  if [ $1 = "l" ]; then
    echo "Mounting l to desktop..."
    sshfs l:/home/josh/Desktop ~/Desktop/mc_remote -o volname=l_remote
  fi
  if [ $1 = "be" ]; then
    echo "Mounting be to desktop..."
    sshfs be:/ ~/Desktop/be_remote -o volname=be_remote
  fi
  if [ $1 = "d001bjm" ]; then
    echo "Mounting d001bjm to desktop..."
    sshfs be:/ ~/Desktop/d001bjm_remote -o volname=d001bjm_remote
  fi
}

be_repos () {
  RDIR=$(PWD)

  if [ $1 = "all" ] || [ $1 = "bcl" ]; then
    CURRENT=bcl
    FILE_CURRENT=blockcommonlib
    cd /Users/joshuabell/projects/block_empires/block-common-lib
    echo
    if [ -z "$3" ]; then figlet "bcl"; fi
    eval $2
    echo
    echo "Done with $CURRENT...."
  fi

#  if [ $1 = "all" ] || [ $1 = "action" ]; then
#    CURRENT=action
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/action
#    echo
#    if [ -z "$3" ]; then figlet Action-lib; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi

  if [ $1 = "all" ] || [ $1 = "veh" ]; then
    CURRENT=veh
    FILE_CURRENT=JedicraftVehicles
    cd /Users/joshuabell/projects/block_empires/JedicraftVehicles
    echo
    if [ -z "$3" ]; then figlet Vehicles; fi
    eval $2
    echo
    echo "Done with $CURRENT...."
  fi

  if [ $1 = "all" ] || [ $1 = "players" ]; then
    CURRENT=players
    FILE_CURRENT=JedicraftPlayers
    cd /Users/joshuabell/projects/block_empires/JedicraftPlayers
    echo
    if [ -z "$3" ]; then figlet Players; fi
    eval $2
    echo
    echo "Done with $CURRENT...."
  fi

#  if [ $1 = "all" ] || [ $1 = "spells" ]; then
#    CURRENT=spells
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/spells
#    echo
#    if [ -z "$3" ]; then figlet Spells; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi
#
#  if [ $1 = "all" ] || [ $1 = "core" ]; then
#    CURRENT=core
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/core
#    echo
#    if [ -z "$3" ]; then figlet Empires Core; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi
#
#  if [ $1 = "all" ] || [ $1 = "mobs" ]; then
#    CURRENT=mobs
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/mobs
#    echo
#    if [ -z "$3" ]; then figlet Mobs; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi
#
#  if [ $1 = "all" ] || [ $1 = "wedit" ]; then
#    CURRENT=wedit
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/wedit
#    echo
#    if [ -z "$3" ]; then figlet WEdit; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi
#
#  if [ $1 = "all" ] || [ $1 = "chestshop" ]; then
#    CURRENT=chestshop
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/chestshop
#    echo
#    if [ -z "$3" ]; then figlet ChestShop; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi
#
#  if [ $1 = "all" ] || [ $1 = "structure" ]; then
#    CURRENT=structure
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/structure
#    echo
#    if [ -z "$3" ]; then figlet Structure; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi
#
#  if [ $1 = "all" ] || [ $1 = "generator" ]; then
#    CURRENT=generator
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/generator
#    echo
#    if [ -z "$3" ]; then figlet Generator; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi
#
#  if [ $1 = "all" ] || [ $1 = "region" ]; then
#    CURRENT=region
#    FILE_CURRENT=$CURRENT
#    cd /Users/joshuabell/projects/block_empires/region
#    echo
#    if [ -z "$3" ]; then figlet Region; fi
#    eval $2
#    echo
#    echo "Done with $CURRENT...."
#  fi

  echo
  echo "returning to $RDIR"
  cd $RDIR
}

be_master () {
  cmd=master
  be_repos ${1:-all} $cmd
}

be_status () {
  cmd=status
  be_repos ${1:-all} $cmd
}

be_push() {
  cmd='gam "generic commit message" && push'
  be_repos ${1:-all} $cmd
}

be_jars() {
  cmd='RET="$PWD" &&\
  cd ~/Desktop/plugin-archives/empires &&\
  find ~/Desktop/plugin-archives/empires -type f -iname "*$FILE_CURRENT*" -exec rm {} + &&\
  cd "$RET" &&\
  cp -v $(find . -not -path "./gradle/*" -not -path "./libs/*" -not -path "./lib/*" -type f -iname "*.jar" | head -n1) ~/Desktop/plugin-archives/empires'
  be_repos ${1:-all} $cmd $2
}

be_build() {
  cmd='rm -rf build &&\
  if [ $(basename $(pwd)) = "core" ]; then psql -c "DROP DATABASE IF EXISTS empires_core;" && psql -c "CREATE DATABASE empires_core;" && gradle fullMigrate ; fi &&\
  gradle build && gradle publishToMavenLocal &&\
  be_jars "$CURRENT" noascii'
  be_repos ${1:-all} $cmd $2
}

# minecraft stuff
mcserve() {
  java -Xms10G \
    -Xmx10G \
    -XX:+UseG1GC \
    -XX:+ParallelRefProcEnabled \
    -XX:MaxGCPauseMillis=200 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+DisableExplicitGC \
    -XX:+AlwaysPreTouch \
    -XX:G1NewSizePercent=30 \
    -XX:G1MaxNewSizePercent=40 \
    -XX:G1HeapRegionSize=8M \
    -XX:G1ReservePercent=20 \
    -XX:G1HeapWastePercent=5 \
    -XX:G1MixedGCCountTarget=4 \
    -XX:InitiatingHeapOccupancyPercent=15 \
    -XX:G1MixedGCLiveThresholdPercent=90 \
    -XX:G1RSetUpdatingPauseTimePercent=5 \
    -XX:SurvivorRatio=32 \
    -XX:+PerfDisableSharedMem \
    -XX:MaxTenuringThreshold=1 \
    -Dusing.aikars.flags=https://mcflags.emc.gs \
    -Daikars.new.flags=true \
    -jar $@
}

mcserve_low() {
  java \
  -Xms2G -Xmx2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar $@
}
